import{a as f,S as y,i}from"./assets/vendor-73qhTu8_.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();const m="55695141-df1ad6569c10fb966400a1286",d="https://pixabay.com/api/";async function g(e){const s={key:m,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0};return(await f.get(d,{params:s})).data}let h=new y(".gallery a",{captionsData:"alt",captionDelay:250});function b(e){return e.map(({webformatURL:s,largeImageURL:o,tags:a,likes:t,views:r,comments:n,downloads:u})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${o}">
          <img class="gallery-image" src="${s}" alt="${a}" loading="lazy" />
          <div class="info">
            <p class="info-item"><b>Likes</b><span>${t}</span></p>
            <p class="info-item"><b>Views</b><span>${r}</span></p>
            <p class="info-item"><b>Comments</b><span>${n}</span></p>
            <p class="info-item"><b>Downloads</b><span>${u}</span></p>
          </div>
        </a>
      </li>`).join("")}function L(e,s){e.style.display="flex";const o=b(s);e.innerHTML=o,h.refresh()}function w(e){e.innerHTML="",e.style.display="none"}function P(e){e.style.display="flex"}function S(e){e.style.display="none"}const l=document.querySelector(".form"),c=document.querySelector(".gallery"),p=document.querySelector(".loader-container");l.addEventListener("submit",e=>{e.preventDefault();const s=e.currentTarget.elements.searchQuery.value.trim();if(s===""){i.error({title:"Error",message:"The search field cannot be empty! Please enter a query.",position:"topRight"});return}w(c),P(p),g(s).then(o=>{if(o.hits.length===0){i.warning({title:"Caution",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}L(c,o.hits)}).catch(o=>{i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error("API Error:",o)}).finally(()=>{S(p),l.reset()})});
//# sourceMappingURL=index.js.map
